### ISSUE TITLE
missing double dash in command line vsearch

### ISSUE THREAD

**Issue by dridk** [mlangill/microbiome_helper#2]
You forgot double dash everywhere. 
For instance : 

      vsearch -derep_fulllength stool_sequences.fasta -output cluster/unique.fasta -sizeout -minseqlength 50
      vsearch --derep_fulllength stool_sequences.fasta --output cluster/unique.fasta --sizeout --minseqlength 50

**Comment by gavinmdouglas** [comment]
I'm not sure I follow - are you referring to our wrapper script "chimera_filter.pl"? If you're referring to vsearch itself the GitHub page is here: https://github.com/torognes/vsearch

**Comment by dridk** [comment]
Oups.. I was too fast ! Sorry ! I fogot to mention where does it take place  ! 
On the wiki =>  https://github.com/mlangill/microbiome_helper/wiki/16S-tutorial-for-CCBC

**Comment by dridk** [comment]
From the vsearch documentation, it's : 

      vsearch --derep_fulllength  

And not : 

      vsearch -derep_fulllength

**Comment by gavinmdouglas** [comment]
Thanks for pointing that out, I switched to "--" for clarity.
