### ISSUE TITLE
No pre-computed_results in Metagenomic Tutorial Data

### ISSUE THREAD

**Issue by blue-moon22** [mlangill/microbiome_helper#3]
Could you upload the pre-computed_results directory in the tutorial data download?
Thanks,
Vicky

**Comment by gavinmdouglas** [comment]
Hi Vicky,

If you’re looking at the tutorial here (https://github.com/mlangill/microbiome_helper/wiki/Metagenomics-Tutorial-(Downsampled) <https://github.com/mlangill/microbiome_helper/wiki/Metagenomics-Tutorial-(Downsampled)>) then the pre-calculated folder is part of the Tutorial Data download link (https://www.dropbox.com/s/ofulbuie6kuc1w2/hmp_metagenomics_downsampled.zip?dl=1 <https://www.dropbox.com/s/ofulbuie6kuc1w2/hmp_metagenomics_downsampled.zip?dl=1>).


Cheers,

Gavin

**Comment by blue-moon22** [comment]
Got it, thanks!
