### ISSUE TITLE
Can I do denovo chimeric detection with MBH

### ISSUE THREAD

**Issue by caijian89** [mlangill/microbiome_helper#8]
Hello！
I am a fresh man with the bioinformatic analysis of microbial community. You MBH is really awesome and helpful.  
 I have a question with the chimer filter process as following: Can I do a denovo chimeric detection with your pipeline, and how to do it within your Vitural system.

**Comment by gavinmdouglas** [comment]
Hey there,

We don’t have a script to run de novo chimera checking, but I’ve added some example commands to our wiki site:
https://github.com/mlangill/microbiome_helper/wiki/Remove-chimeric-reads#de-novo-chimera-checking <https://github.com/mlangill/microbiome_helper/wiki/Remove-chimeric-reads#de-novo-chimera-checking>

Let me know if you have any questions.

Cheers,

Gavin

**Comment by caijian89** [comment]
Hi Gavin！
Great thanks for your helpful reply. 
^_^

Jian
