### ISSUE TITLE
Assign Taxonomy with RDP classifer

### ISSUE THREAD

**Issue by caijian89** [mlangill/microbiome_helper#9]
HI Garvin！
Sorry for bothering you again.

I try to add the RDP  naïve Bayesian classifier for taxonomy assignment, which included in open-reference OTU picking workflow. I had added some sentence in the clustering parameters file as following:

> echo "assign_taxonomy:assignment_method rdp" >> clustering_params.txt
echo "assign_taxonomy:confidence 0.8" >> clustering_params.txt

Then it warned error happened, the warning message  was list as below:

*** ERROR RAISED DURING STEP: Assign taxonomy
Command run was:
 assign_taxonomy.py -o /home/mh_user/Data/16S/anoxic/clustering//rdp_assigned_taxonomy -i /home/mh_user/Data/16S/anoxic/clustering//rep_set.fna --confidence 0.8 --id_to_taxonomy_fp /home/shared/rRNA_db/99_taxonomy_7_levels.txt --assignment_method rdp --reference_seqs_fp /home/shared/rRNA_db/99_otus_16S.fasta
Command returned exit status: 2
Stdout:

Stderr
Error in assign_taxonomy.py: RDP classifier is not installed or not accessible to QIIME. See install instructions here: http://qiime.org/install/install.html#rdp-install

If you need help with QIIME, see:
http://help.qiime.org

Could you help with that?

Good Weekends!

Jian

**Comment by gavinmdouglas** [comment]
Hey again,

The RDP classifier isn’t installed on the virtual box at the moment, but you can quickly install it by downloading the source code from here: http://qiime.org/install/alternative.html <http://qiime.org/install/alternative.html> and by following the instructions here: http://qiime.org/install/alternative.html#rdp-jar-path-environment-variable. <http://qiime.org/install/alternative.html#rdp-jar-path-environment-variable.%5C>


Best,

Gavin

**Comment by caijian89** [comment]
Hey, ~~ Maybe a good afternoon for you?

Thank you kind help, it really works as your word!

Good day

Jian
